In [39]:
import numpy as np

array1 = np.random.randint(1, 100, (1,10))
print('first: ' + str(array1[0][0]))
print('last: ' + str(array1[0][9]))

array2 = np.random.random((3,3))
print(array2)

first: 2
last: 50
[[0.70908815 0.29383131 0.40788205]
 [0.37071859 0.16579024 0.28109719]
 [0.88906197 0.13509893 0.60517492]]


In [15]:
print(array2[0,:])
print(array2[:,2])

#create/print sub-array
subarray = array2[:2,:2]
print(subarray)

[0.19299992 0.55102309 0.14489336]
[0.14489336 0.3739641  0.50723421]
[[0.19299992 0.55102309]
 [0.2021848  0.85496914]]


In [33]:
a1 = np.random.randint(low=0, high=100, size=5)
a2 = np.random.randint(low=0, high=100, size=5)
print(a1)
print(a2)
added = a1 + a2
print(added)

mult = a1 * a2
print(mult)

sqr = a1 ** 2
print(sqr)

[99 72 29 43 53]
[26 12 46 54 33]
[125  84  75  97  86]
[2574  864 1334 2322 1749]
[9801 5184  841 1849 2809]


In [37]:
arr1 = np.random.randint(low=0, high=100, size=(2,3))
arr2 = np.random.randint(low=0, high=100, size=(3,2))
print(arr1)
print(arr2)
dotmul = np.dot(arr1, arr2)
print(dotmul)

[[27 42 47]
 [52  1 78]]
[[92 99]
 [61 97]
 [77 73]]
[[ 8665 10178]
 [10851 10939]]


In [38]:
elmul = arr1 * arr2
print(elmul)

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

because of their different array shapes, arr1 and arr2 cannot be multiplied together element-wise.